apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Using the official Jetstack google-cas-issuer installation manifest
  - google-cas-issuer-v0.7.1.yaml
  - wif-configmap.yaml

# Patch the deployment to configure Workload Identity Federation (WIF)
patches:
  - path: wif-patch.yaml

namespace: platform-clm
