apiVersion: v1
kind: Service
metadata:
  name: cert-manager-google-cas-issuer-metrics
  labels:
    app: cert-manager-google-cas-issuer
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9402"
spec:
  selector:
    app: cert-manager-google-cas-issuer
  ports:
    - name: metrics
      port: 9402
      targetPort: 9402
      protocol: TCP
